env:
  global:
    - CC_TEST_REPORTER_ID=3805c1099ea8657e7966cfe13a6e48bff0f64d8eb7756925f032306422479f23
    - TRAVIS_RUN=1
language: node_js
node_js:
  - "12"
cache: yarn
before_script:
  # Do nothing
script:
  #
  -
after_script:
  # Generate test coverage and send to code climate
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - npm test -- --coverage
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
